name: DereeIntroBigData
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - ipykernel
  - jupyter
  - jupyterlab
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - ipywidgets
  - pip
  - pip:
      - hypertools==0.8.1
      - ipympl==0.9.8
      - ppca==0.0.4
      - pymysql==1.1.2
      - pynndescent==0.5.13
      - tensorly==0.9.0
      - umap-learn==0.5.9.post2
      - notebook==7.0.5
      - widgetsnbextension==4.0.15
      - chardet
